export enum IconImages {
  arrow = 'arrow',
  backArrow = 'backArrow',
  bag = 'bag',
  barcode = 'barcode',
  box = 'box',
  burger = 'burger',
  cancel = 'cancel',
  container = 'container',
  cross = 'cross',
  done = 'done',
  edit = 'edit',
  error = 'error',
  errorImage = 'errorImage',
  info = 'info',
  kebab = 'kebab',
  keyboard = 'keyboard',
  keyboardDelete = 'keyboardDelete',
  market = 'market',
  qrCode = 'qrCode',
  qrCodeDone = 'qrCodeDone',
  rocket = 'rocket',
  success = 'success',
  warningFilled = 'warningFilled',
  warningOutline = 'warningOutline',
  yaLogo = 'yaLogo',
  yaLogoname = 'yaLogoname',
}

export default IconImages;
